name: Build and Release SUFFERING Server

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: windows
            goarch: amd64
            output: SUFFERING-Server-windows-x64.exe

          - goos: windows
            goarch: arm64
            output: SUFFERING-Server-windows-arm64.exe

          - goos: linux
            goarch: amd64
            output: SUFFERING-Server-linux-x64

          - goos: linux
            goarch: arm64
            output: SUFFERING-Server-linux-arm64

          - goos: darwin
            goarch: amd64
            output: SUFFERING-Server-macos-intel

          - goos: darwin
            goarch: arm64
            output: SUFFERING-Server-macos-silicon

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          mkdir -p dist

          go build \
            -trimpath \
            -ldflags="-s -w" \
            -o dist/${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: dist/${{ matrix.output }}


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        run: |
          mkdir release

          find artifacts -type f -exec cp {} release/ \;

          ls -la release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
